export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const FILL_CITY_AUTOCOMPLETE = 'FILL_CITY_AUTOCOMPLETE';
export const OPEN_CITY_LIST = 'OPEN_CITY_LIST';
export const CLOSE_CITY_LIST = 'CLOSE_CITY_LIST';
export const CHECK_CITY_WEATHER = 'CHECK_CITY_WEATHER';
